name: Deploy WebApp
on:
  push:
    branches:
      - master

jobs:
  deploy-development:
    name: Deploy to development
    environment: 'development'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo 'Deploy to production'


  deploy-production:
    needs: deploy-development
    environment: 'production'
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo 'Deploy to production'