name: Production deployment
on:
  push:
    branches:
      - production

jobs:
  deploy-production-trigger:
    name: Production deployment
    runs-on: ubuntu-latest
    steps:
      - name: Production deployment
        run: echo 'Production deployment'
